apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce  # Allows read/write by one node
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Uses the "standard" StorageClass for dynamic provisioning