apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  url: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQGRiLXNlcnZpY2U6NTQzMg==
  # Example:
  # password: {{ .Values.password | b64enc }}