apiVersion: v1
kind: Service
metadata:
  name: headless-service
  namespace: db-namespace
spec:
  selector:
    app: db
  clusterIP: None
  ports:
  - name: db
    protocol: TCP
    port: 5000
    targetPort: 5000
