apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.deploy.name }}-deployment
  namespace: {{ .Values.deploy.namespace }}
  labels:
    app:  {{ .Values.deploy.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Values.deploy.name }}
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  {{ .Values.deploy.name }}
        image:  {{ .Values.deploy.image }}
        ports:
        - containerPort:  {{ .Values.deploy.port }}
          name:  {{ .Values.deploy.name }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always