apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.deploy.name }}-hpa
  namespace: {{ .Values.deploy.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deploy.name }}-deployment
  minReplicas: {{ .Values.resources.hpa.minReplicas }}
  maxReplicas: {{ .Values.resources.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resources.hpa.targetCPUUtilizationPercentage }}
